### ISSUE TITLE
rsync fails in Github Actions runner

### ISSUE THREAD

**Issue by davereid-pfg** [pantheon-systems/terminus-rsync-plugin#27]
I have the following workflow file:

```yaml
# @file
# Deploys traffic metrics data to a Pantheon environment private files directory.

name: Pantheon Traffic

# When does this job run?
# - For every 6 hours
# - On manual workflow run
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      PANTHEON_SITE: ${{ secrets.PANTHEON_SITE }}
    steps:
      - name: Install SSH key for Pantheon Git repository
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.PANTHEON_SSH_KEY }}
          # We will manually keyscan below
          known_hosts: unnecessary
      - name: Install PHP and Terminus
        uses: shivammathur/setup-php@v2
        with:
          tools: pantheon-systems/terminus:3
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Set the PANTHEON_SITE environment variable using Github repository name
        if: ${{ !env.PANTHEON_SITE }}
        run: echo "PANTHEON_SITE=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
      - name: Authenticate Terminus
        run: terminus auth:login --machine-token=${{ SECRETS.PANTHEON_MACHINE_TOKEN }}
      - name: Get the Pantheon site UUID
        run: echo "PANTHEON_SITE_UUID=$(terminus site:info $PANTHEON_SITE --field=id)" >> $GITHUB_ENV
      - name: Run ssh-keyscan on dev environment
        run: |
          ssh-keyscan -p 2222 -H appserver.dev.$PANTHEON_SITE_UUID.drush.inc >> ~/.ssh/known_hosts
          for APP_SERVER in `getent hosts appserver.dev.$PANTHEON_SITE_UUID.drush.in | awk '{print $1}'`; do
            ssh-keyscan -p 2222 -H $APP_SERVER >> ~/.ssh/known_hosts
          done
      - name: Intall Terminus Rsync Plugin
        run: terminus -n self:plugin:install terminus-rsync-plugin
      - name: Create empty traffic directory
        run: mkdir ./traffic
      - name: Setup traffic monitoring job
        run: |
          terminus -n env:wake "$PANTHEON_SITE.live"
          terminus -n env:metrics --period month --datapoints auto --format json --fields datetime,visits,pages_served -- "$PANTHEON_SITE.live" > ./traffic/traffic.json
          terminus -n env:metrics --period month --datapoints auto --format csv --fields datetime,visits,pages_served -- "$PANTHEON_SITE.live" > ./traffic/traffic-details.csv
      - name: rysnc traffic files to Pantheon dev environment
        run: terminus -n rsync --yes ./traffic $PANTHEON_SITE.dev:files/private --
```

This fails with the following error in the rsync step:
```
Run terminus -n rsync --yes ./traffic $PANTHEON_SITE.dev:files/private
Notice: ] Running rsync -rlIpz  --temp-dir=~/tmp --delay-updates ./traffic dev.SITE-UUID-REDACTED@appserver.dev.SITE-UUID-REDACTED.drush.in:files/private
Host key verification failed.
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: unexplained error (code 255) at io.c(235) [sender=3.1.3]
Error: ]  Command `rsync -rlIpz  --temp-dir=~/tmp --delay-updates --ipv4 --exclude=.git -e 'ssh -p 2222' './traffic' 'dev.SITE-UUID-REDACTED@appserver.dev.SITE-UUID-REDACTED.drush.in:files/private' ` failed with exit code 255 
Error: Process completed with exit code 1.
```
